### ISSUE TITLE
Tracking Issue for UI

### ISSUE THREAD

**Issue by Montessquio** [Montessquio/ChainDB#1]
This is the tracking issue for UI styling and functionality.

---

To Do:
- [ ] Create responsive Web CSS
- [ ] Make frontend mobile-friendly.
- [ ] Implement search term tokenizer.
- [ ] Allow search results to be seen as a list or as thumbnails.
- [ ] Implement user accounts.
- [ ] Allow permission-based feature restriction of user accounts.

**Comment by Montessquio** [comment]
As of b4cd386, the web UI renders poorly on laptop and HiDPI screens.
